#include "dllstub_def.h"

static const char DLL_NAME[]="lz32.nt.dll";

DEFINE_FUNC2(CopyLZFile)
DEFINE_FUNC2(GetExpandedNameA)
DEFINE_FUNC2(GetExpandedNameW)
DEFINE_FUNC1(LZClose)
DEFINE_FUNC2(LZCopy)
DEFINE_FUNC0(LZDone)
DEFINE_FUNC1(LZInit)
DEFINE_FUNC3(LZOpenFileA)
DEFINE_FUNC3(LZOpenFileW)
DEFINE_FUNC3(LZRead)
DEFINE_FUNC3(LZSeek)
DEFINE_FUNC0(LZStart)
