#include "dllyact_def.h"

extern "C" DW Redirect(DW Org);

#define DEFINE_FUNC_REDIR1(name) 	\
EXTERN_C DW STUB_IMPORT name(DW);	\
EXTERN_C DW STUB_EXPORT yact_##name(DW *R)		\
{	\
  DW r=name(Redirect(p1));	\
  LEAVE(1);		\
  return r;		\
}

#define DEFINE_FUNC_REDIR2(name) 	\
EXTERN_C DW STUB_IMPORT name(DW,DW);	\
EXTERN_C DW STUB_EXPORT yact_##name(DW *R)		\
{	\
  DW r=name(Redirect(p1),p2);	\
  LEAVE(2);		\
  return r;		\
}

#define DEFINE_FUNC_REDIR3(name) 	\
EXTERN_C DW STUB_IMPORT name(DW,DW,DW);	\
EXTERN_C DW STUB_EXPORT yact_##name(DW *R)		\
{	\
  DW r=name(Redirect(p1),p2,p3);	\
  LEAVE(3);		\
  return r;		\
}

#define DEFINE_FUNC_REDIR4(name) 	\
EXTERN_C DW STUB_IMPORT name(DW,DW,DW,DW);	\
EXTERN_C DW STUB_EXPORT yact_##name(DW *R)		\
{	\
  DW r=name(Redirect(p1),p2,p3,p4);	\
  LEAVE(4);		\
  return r;		\
}

#define DEFINE_FUNC_REDIR5(name) 	\
EXTERN_C DW STUB_IMPORT name(DW,DW,DW,DW,DW);	\
EXTERN_C DW STUB_EXPORT yact_##name(DW *R)		\
{	\
  DW r=name(Redirect(p1),p2,p3,p4,p5);	\
  LEAVE(5);		\
  return r;		\
}

#define DEFINE_FUNC_REDIR6(name) 	\
EXTERN_C DW STUB_IMPORT name(DW,DW,DW,DW,DW,DW);	\
EXTERN_C DW STUB_EXPORT yact_##name(DW *R)		\
{	\
  DW r=name(Redirect(p1),p2,p3,p4,p5,p6);	\
  LEAVE(6);		\
  return r;		\
}

#define DEFINE_FUNC_REDIR7(name) 	\
EXTERN_C DW STUB_IMPORT name(DW,DW,DW,DW,DW,DW,DW);	\
EXTERN_C DW STUB_EXPORT yact_##name(DW *R)		\
{	\
  DW r=name(Redirect(p1),p2,p3,p4,p5,p6,p7);	\
  LEAVE(7);		\
  return r;		\
}

#define DEFINE_FUNC_REDIR8(name) 	\
EXTERN_C DW STUB_IMPORT name(DW,DW,DW,DW,DW,DW,DW,DW);	\
EXTERN_C DW STUB_EXPORT yact_##name(DW *R)		\
{	\
  DW r=name(Redirect(p1),p2,p3,p4,p5,p6,p7,p8);	\
  LEAVE(8);		\
  return r;		\
}

#define DEFINE_FUNC_REDIR9(name) 	\
EXTERN_C DW STUB_IMPORT name(DW,DW,DW,DW,DW,DW,DW,DW,DW);	\
EXTERN_C DW STUB_EXPORT yact_##name(DW *R)		\
{	\
  DW r=name(Redirect(p1),p2,p3,p4,p5,p6,p7,p8,p9);	\
  LEAVE(8);		\
  return r;		\
}

#define DEFINE_FUNC_REDIR12(name) 	\
EXTERN_C DW STUB_IMPORT name(DW,DW,DW,DW,DW,DW,DW,DW,DW,DW,DW,DW);	\
EXTERN_C DW STUB_EXPORT yact_##name(DW *R)		\
{	\
  DW r=name(Redirect(p1),p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12);	\
  LEAVE(8);		\
  return r;		\
}

DEFINE_FUNC1(AbortSystemShutdownA)
DEFINE_FUNC1(AbortSystemShutdownW)
DEFINE_FUNC8(AccessCheck)
DEFINE_FUNC11(AccessCheckAndAuditAlarmA)
DEFINE_FUNC11(AccessCheckAndAuditAlarmW)
DEFINE_FUNC11(AccessCheckByType)
DEFINE_FUNC16(AccessCheckByTypeAndAuditAlarmA)
DEFINE_FUNC16(AccessCheckByTypeAndAuditAlarmW)
DEFINE_FUNC11(AccessCheckByTypeResultList)
DEFINE_FUNC16(AccessCheckByTypeResultListAndAuditAlarmA)
DEFINE_FUNC17(AccessCheckByTypeResultListAndAuditAlarmByHandleA)
DEFINE_FUNC17(AccessCheckByTypeResultListAndAuditAlarmByHandleW)
DEFINE_FUNC16(AccessCheckByTypeResultListAndAuditAlarmW)
DEFINE_FUNC4(AddAccessAllowedAce)
DEFINE_FUNC5(AddAccessAllowedAceEx)
DEFINE_FUNC7(AddAccessAllowedObjectAce)
DEFINE_FUNC4(AddAccessDeniedAce)
DEFINE_FUNC5(AddAccessDeniedAceEx)
DEFINE_FUNC7(AddAccessDeniedObjectAce)
DEFINE_FUNC5(AddAce)
DEFINE_FUNC6(AddAuditAccessAce)
DEFINE_FUNC7(AddAuditAccessAceEx)
DEFINE_FUNC9(AddAuditAccessObjectAce)
DEFINE_FUNC2(AddUsersToEncryptedFile)
DEFINE_FUNC6(AdjustTokenGroups)
DEFINE_FUNC6(AdjustTokenPrivileges)
DEFINE_FUNC11(AllocateAndInitializeSid)
DEFINE_FUNC1(AllocateLocallyUniqueId)
DEFINE_FUNC2(AreAllAccessesGranted)
DEFINE_FUNC2(AreAnyAccessesGranted)
DEFINE_FUNC2(BackupEventLogA)
DEFINE_FUNC2(BackupEventLogW)
DEFINE_FUNC5(BuildExplicitAccessWithNameA)
DEFINE_FUNC5(BuildExplicitAccessWithNameW)
DEFINE_FUNC6(BuildImpersonateExplicitAccessWithNameA)
DEFINE_FUNC6(BuildImpersonateExplicitAccessWithNameW)
DEFINE_FUNC2(BuildImpersonateTrusteeA)
DEFINE_FUNC2(BuildImpersonateTrusteeW)
DEFINE_FUNC9(BuildSecurityDescriptorA)
DEFINE_FUNC9(BuildSecurityDescriptorW)
DEFINE_FUNC2(BuildTrusteeWithNameA)
DEFINE_FUNC2(BuildTrusteeWithNameW)
DEFINE_FUNC6(BuildTrusteeWithObjectsAndNameA)
DEFINE_FUNC6(BuildTrusteeWithObjectsAndNameW)
DEFINE_FUNC5(BuildTrusteeWithObjectsAndSidA)
DEFINE_FUNC5(BuildTrusteeWithObjectsAndSidW)
DEFINE_FUNC2(BuildTrusteeWithSidA)
DEFINE_FUNC2(BuildTrusteeWithSidW)
DEFINE_FUNC1(CancelOverlappedAccess)
DEFINE_FUNC3(ChangeServiceConfig2A)
DEFINE_FUNC3(ChangeServiceConfig2W)
DEFINE_FUNC11(ChangeServiceConfigA)
DEFINE_FUNC11(ChangeServiceConfigW)
DEFINE_FUNC3(CheckTokenMembership)
DEFINE_FUNC2(ClearEventLogA)
DEFINE_FUNC2(ClearEventLogW)
DEFINE_FUNC1(CloseEncryptedFileRaw)
DEFINE_FUNC1(CloseEventLog)
//DEFINE_FUNC1(CloseServiceHandle)
DEFINE_FUNC2(CloseTrace)
DEFINE_FUNC3(CommandLineFromMsiDescriptor)
DEFINE_FUNC3(ControlService)
DEFINE_FUNC5(ControlTraceA)
DEFINE_FUNC5(ControlTraceW)
DEFINE_FUNC5(ConvertAccessToSecurityDescriptorA)
DEFINE_FUNC5(ConvertAccessToSecurityDescriptorW)
DEFINE_FUNC6(ConvertSDToStringSDRootDomainA)
DEFINE_FUNC6(ConvertSDToStringSDRootDomainW)
DEFINE_FUNC7(ConvertSecurityDescriptorToAccessA)
DEFINE_FUNC7(ConvertSecurityDescriptorToAccessNamedA)
DEFINE_FUNC7(ConvertSecurityDescriptorToAccessNamedW)
DEFINE_FUNC7(ConvertSecurityDescriptorToAccessW)
DEFINE_FUNC5(ConvertSecurityDescriptorToStringSecurityDescriptorA)
DEFINE_FUNC5(ConvertSecurityDescriptorToStringSecurityDescriptorW)
DEFINE_FUNC2(ConvertSidToStringSidA)
DEFINE_FUNC2(ConvertSidToStringSidW)
DEFINE_FUNC5(ConvertStringSDToSDRootDomainA)
DEFINE_FUNC5(ConvertStringSDToSDRootDomainW)
DEFINE_FUNC4(ConvertStringSecurityDescriptorToSecurityDescriptorA)
DEFINE_FUNC4(ConvertStringSecurityDescriptorToSecurityDescriptorW)
DEFINE_FUNC2(ConvertStringSidToSidA)
DEFINE_FUNC2(ConvertStringSidToSidW)
DEFINE_FUNC6(ConvertToAutoInheritPrivateObjectSecurity)
DEFINE_FUNC3(CopySid)
DEFINE_FUNC6(CreatePrivateObjectSecurity)
DEFINE_FUNC8(CreatePrivateObjectSecurityEx)
DEFINE_FUNC11(CreateProcessAsUserA)
DEFINE_FUNC11(CreateProcessAsUserW)
DEFINE_FUNC11(CreateProcessWithLogonW)
DEFINE_FUNC9(CreateRestrictedToken)
DEFINE_FUNC13(CreateServiceA)
DEFINE_FUNC13(CreateServiceW)
DEFINE_FUNC2(CreateTraceInstanceId)
DEFINE_FUNC5(CryptAcquireContextA)
DEFINE_FUNC5(CryptAcquireContextW)
DEFINE_FUNC3(CryptContextAddRef)
DEFINE_FUNC5(CryptCreateHash)
DEFINE_FUNC6(CryptDecrypt)
DEFINE_FUNC5(CryptDeriveKey)
DEFINE_FUNC1(CryptDestroyHash)
DEFINE_FUNC1(CryptDestroyKey)
DEFINE_FUNC4(CryptDuplicateHash)
DEFINE_FUNC4(CryptDuplicateKey)
DEFINE_FUNC7(CryptEncrypt)
DEFINE_FUNC6(CryptEnumProviderTypesA)
DEFINE_FUNC6(CryptEnumProviderTypesW)
DEFINE_FUNC6(CryptEnumProvidersA)
DEFINE_FUNC6(CryptEnumProvidersW)
DEFINE_FUNC6(CryptExportKey)
DEFINE_FUNC4(CryptGenKey)
DEFINE_FUNC3(CryptGenRandom)
DEFINE_FUNC5(CryptGetDefaultProviderA)
DEFINE_FUNC5(CryptGetDefaultProviderW)
DEFINE_FUNC5(CryptGetHashParam)
DEFINE_FUNC5(CryptGetKeyParam)
DEFINE_FUNC5(CryptGetProvParam)
DEFINE_FUNC3(CryptGetUserKey)
DEFINE_FUNC4(CryptHashData)
DEFINE_FUNC3(CryptHashSessionKey)
DEFINE_FUNC6(CryptImportKey)
DEFINE_FUNC2(CryptReleaseContext)
DEFINE_FUNC4(CryptSetHashParam)
DEFINE_FUNC4(CryptSetKeyParam)
DEFINE_FUNC4(CryptSetProvParam)
DEFINE_FUNC2(CryptSetProviderA)
DEFINE_FUNC4(CryptSetProviderExA)
DEFINE_FUNC4(CryptSetProviderExW)
DEFINE_FUNC2(CryptSetProviderW)
DEFINE_FUNC6(CryptSignHashA)
DEFINE_FUNC6(CryptSignHashW)
DEFINE_FUNC6(CryptVerifySignatureA)
DEFINE_FUNC6(CryptVerifySignatureW)
DEFINE_FUNC2(DecryptFileA)
DEFINE_FUNC2(DecryptFileW)
DEFINE_FUNC2(DeleteAce)
DEFINE_FUNC1(DeleteService)
DEFINE_FUNC1(DeregisterEventSource)
DEFINE_FUNC1(DestroyPrivateObjectSecurity)
DEFINE_FUNC3(DuplicateToken)
DEFINE_FUNC6(DuplicateTokenEx)
DEFINE_FUNC2(ElfBackupEventLogFileA)
DEFINE_FUNC2(ElfBackupEventLogFileW)
DEFINE_FUNC2(ElfChangeNotify)
DEFINE_FUNC2(ElfClearEventLogFileA)
DEFINE_FUNC2(ElfClearEventLogFileW)
DEFINE_FUNC1(ElfCloseEventLog)
DEFINE_FUNC1(ElfDeregisterEventSource)
DEFINE_FUNC2(ElfNumberOfRecords)
DEFINE_FUNC2(ElfOldestRecord)
DEFINE_FUNC3(ElfOpenBackupEventLogA)
DEFINE_FUNC3(ElfOpenBackupEventLogW)
DEFINE_FUNC3(ElfOpenEventLogA)
DEFINE_FUNC3(ElfOpenEventLogW)
DEFINE_FUNC7(ElfReadEventLogA)
DEFINE_FUNC7(ElfReadEventLogW)
DEFINE_FUNC3(ElfRegisterEventSourceA)
DEFINE_FUNC3(ElfRegisterEventSourceW)
DEFINE_FUNC12(ElfReportEventA)
DEFINE_FUNC12(ElfReportEventW)
DEFINE_FUNC6(EnableTrace)
DEFINE_FUNC1(EncryptFileA)
DEFINE_FUNC1(EncryptFileW)
DEFINE_FUNC2(EncryptionDisable)
DEFINE_FUNC6(EnumDependentServicesA)
DEFINE_FUNC6(EnumDependentServicesW)
DEFINE_FUNC9(EnumServiceGroupW)
DEFINE_FUNC8(EnumServicesStatusA)
DEFINE_FUNC10(EnumServicesStatusExA)
DEFINE_FUNC10(EnumServicesStatusExW)
DEFINE_FUNC8(EnumServicesStatusW)
DEFINE_FUNC2(EqualPrefixSid)
DEFINE_FUNC2(EqualSid)
DEFINE_FUNC2(FileEncryptionStatusA)
DEFINE_FUNC2(FileEncryptionStatusW)
DEFINE_FUNC2(FindFirstFreeAce)
DEFINE_FUNC1(FreeEncryptionCertificateHashList)
DEFINE_FUNC1(FreeSid)
DEFINE_FUNC9(GetAccessPermissionsForObjectA)
DEFINE_FUNC9(GetAccessPermissionsForObjectW)
DEFINE_FUNC3(GetAce)
DEFINE_FUNC4(GetAclInformation)
DEFINE_FUNC4(GetAuditedPermissionsFromAclA)
DEFINE_FUNC4(GetAuditedPermissionsFromAclW)
DEFINE_FUNC1(GetCurrentHwProfileA)
DEFINE_FUNC1(GetCurrentHwProfileW)
DEFINE_FUNC3(GetEffectiveRightsFromAclA)
DEFINE_FUNC3(GetEffectiveRightsFromAclW)
DEFINE_FUNC5(GetEventLogInformation)
DEFINE_FUNC3(GetExplicitEntriesFromAclA)
DEFINE_FUNC3(GetExplicitEntriesFromAclW)
DEFINE_FUNC5(GetFileSecurityA)
DEFINE_FUNC5(GetFileSecurityW)
DEFINE_FUNC10(GetInheritanceSourceA)
DEFINE_FUNC10(GetInheritanceSourceW)
DEFINE_FUNC5(GetKernelObjectSecurity)
DEFINE_FUNC1(GetLengthSid)
DEFINE_FUNC3(GetLocalManagedApplications)
DEFINE_FUNC5(GetManagedApplications)
DEFINE_FUNC1(GetMultipleTrusteeA)
DEFINE_FUNC1(GetMultipleTrusteeOperationA)
DEFINE_FUNC1(GetMultipleTrusteeOperationW)
DEFINE_FUNC1(GetMultipleTrusteeW)
DEFINE_FUNC8(GetNamedSecurityInfoA)
DEFINE_FUNC9(GetNamedSecurityInfoExA)
DEFINE_FUNC9(GetNamedSecurityInfoExW)
DEFINE_FUNC8(GetNamedSecurityInfoW)
DEFINE_FUNC2(GetNumberOfEventLogRecords)
DEFINE_FUNC2(GetOldestEventLogRecord)
DEFINE_FUNC4(GetOverlappedAccessResults)
DEFINE_FUNC5(GetPrivateObjectSecurity)
DEFINE_FUNC3(GetSecurityDescriptorControl)
DEFINE_FUNC4(GetSecurityDescriptorDacl)
DEFINE_FUNC3(GetSecurityDescriptorGroup)
DEFINE_FUNC1(GetSecurityDescriptorLength)
DEFINE_FUNC3(GetSecurityDescriptorOwner)
DEFINE_FUNC2(GetSecurityDescriptorRMControl)
DEFINE_FUNC4(GetSecurityDescriptorSacl)
DEFINE_FUNC8(GetSecurityInfo)
DEFINE_FUNC9(GetSecurityInfoExA)
DEFINE_FUNC9(GetSecurityInfoExW)
DEFINE_FUNC4(GetServiceDisplayNameA)
DEFINE_FUNC4(GetServiceDisplayNameW)
DEFINE_FUNC4(GetServiceKeyNameA)
DEFINE_FUNC4(GetServiceKeyNameW)
DEFINE_FUNC1(GetSidIdentifierAuthority)
DEFINE_FUNC1(GetSidLengthRequired)
DEFINE_FUNC2(GetSidSubAuthority)
DEFINE_FUNC1(GetSidSubAuthorityCount)
DEFINE_FUNC5(GetTokenInformation)
DEFINE_FUNC2(GetTraceEnableFlags)
DEFINE_FUNC2(GetTraceEnableLevel)
DEFINE_FUNC1(GetTraceLoggerHandle)
DEFINE_FUNC1(GetTrusteeFormA)
DEFINE_FUNC1(GetTrusteeFormW)
DEFINE_FUNC1(GetTrusteeNameA)
DEFINE_FUNC1(GetTrusteeNameW)
DEFINE_FUNC1(GetTrusteeTypeA)
DEFINE_FUNC1(GetTrusteeTypeW)
DEFINE_FUNC2(GetUserNameA)
DEFINE_FUNC2(GetUserNameW)
DEFINE_FUNC5(I_ScSetServiceBitsA)
DEFINE_FUNC5(I_ScSetServiceBitsW)
DEFINE_FUNC1(ImpersonateAnonymousToken)
DEFINE_FUNC1(ImpersonateLoggedOnUser)
DEFINE_FUNC1(ImpersonateNamedPipeClient)
DEFINE_FUNC1(ImpersonateSelf)
DEFINE_FUNC3(InitializeAcl)
DEFINE_FUNC2(InitializeSecurityDescriptor)
DEFINE_FUNC3(InitializeSid)
DEFINE_FUNC5(InitiateSystemShutdownA)
DEFINE_FUNC6(InitiateSystemShutdownExA)
DEFINE_FUNC6(InitiateSystemShutdownExW)
DEFINE_FUNC5(InitiateSystemShutdownW)
DEFINE_FUNC1(InstallApplication)
DEFINE_FUNC3(IsTextUnicode)
DEFINE_FUNC1(IsTokenRestricted)
DEFINE_FUNC1(IsValidAcl)
DEFINE_FUNC1(IsValidSecurityDescriptor)
DEFINE_FUNC1(IsValidSid)
DEFINE_FUNC1(LockServiceDatabase)
DEFINE_FUNC6(LogonUserA)
DEFINE_FUNC6(LogonUserW)
DEFINE_FUNC7(LookupAccountNameA)
DEFINE_FUNC7(LookupAccountNameW)
DEFINE_FUNC7(LookupAccountSidA)
DEFINE_FUNC7(LookupAccountSidW)
DEFINE_FUNC5(LookupPrivilegeDisplayNameA)
DEFINE_FUNC5(LookupPrivilegeDisplayNameW)
DEFINE_FUNC4(LookupPrivilegeNameA)
DEFINE_FUNC4(LookupPrivilegeNameW)
DEFINE_FUNC3(LookupPrivilegeValueA)
DEFINE_FUNC3(LookupPrivilegeValueW)
DEFINE_FUNC7(LookupSecurityDescriptorPartsA)
DEFINE_FUNC7(LookupSecurityDescriptorPartsW)
DEFINE_FUNC4(LsaAddAccountRights)
DEFINE_FUNC2(LsaAddPrivilegesToAccount)
DEFINE_FUNC1(LsaClearAuditLog)
DEFINE_FUNC1(LsaClose)
DEFINE_FUNC4(LsaCreateAccount)
DEFINE_FUNC4(LsaCreateSecret)
DEFINE_FUNC4(LsaCreateTrustedDomain)
DEFINE_FUNC5(LsaCreateTrustedDomainEx)
DEFINE_FUNC1(LsaDelete)
DEFINE_FUNC2(LsaDeleteTrustedDomain)
DEFINE_FUNC4(LsaEnumerateAccountRights)
DEFINE_FUNC5(LsaEnumerateAccounts)
DEFINE_FUNC4(LsaEnumerateAccountsWithUserRight)
DEFINE_FUNC5(LsaEnumeratePrivileges)
DEFINE_FUNC2(LsaEnumeratePrivilegesOfAccount)
DEFINE_FUNC5(LsaEnumerateTrustedDomains)
DEFINE_FUNC5(LsaEnumerateTrustedDomainsEx)
DEFINE_FUNC1(LsaFreeMemory)
DEFINE_FUNC2(LsaGetQuotasForAccount)
DEFINE_FUNC3(LsaGetRemoteUserName)
DEFINE_FUNC2(LsaGetSystemAccessAccount)
DEFINE_FUNC2(LsaGetUserName)
DEFINE_FUNC5(LsaLookupNames)
DEFINE_FUNC4(LsaLookupPrivilegeDisplayName)
DEFINE_FUNC3(LsaLookupPrivilegeName)
DEFINE_FUNC3(LsaLookupPrivilegeValue)
DEFINE_FUNC5(LsaLookupSids)
DEFINE_FUNC1(LsaNtStatusToWinError)
DEFINE_FUNC4(LsaOpenAccount)
DEFINE_FUNC4(LsaOpenPolicy)
DEFINE_FUNC4(LsaOpenSecret)
DEFINE_FUNC4(LsaOpenTrustedDomain)
DEFINE_FUNC4(LsaOpenTrustedDomainByName)
DEFINE_FUNC3(LsaQueryDomainInformationPolicy)
DEFINE_FUNC3(LsaQueryInfoTrustedDomain)
DEFINE_FUNC3(LsaQueryInformationPolicy)
DEFINE_FUNC5(LsaQuerySecret)
DEFINE_FUNC3(LsaQuerySecurityObject)
DEFINE_FUNC4(LsaQueryTrustedDomainInfo)
DEFINE_FUNC4(LsaQueryTrustedDomainInfoByName)
DEFINE_FUNC5(LsaRemoveAccountRights)
DEFINE_FUNC3(LsaRemovePrivilegesFromAccount)
DEFINE_FUNC3(LsaRetrievePrivateData)
DEFINE_FUNC3(LsaSetDomainInformationPolicy)
DEFINE_FUNC3(LsaSetInformationPolicy)
DEFINE_FUNC3(LsaSetInformationTrustedDomain)
DEFINE_FUNC2(LsaSetQuotasForAccount)
DEFINE_FUNC3(LsaSetSecret)
DEFINE_FUNC3(LsaSetSecurityObject)
DEFINE_FUNC2(LsaSetSystemAccessAccount)
DEFINE_FUNC4(LsaSetTrustedDomainInfoByName)
DEFINE_FUNC4(LsaSetTrustedDomainInformation)
DEFINE_FUNC3(LsaStorePrivateData)
DEFINE_FUNC2(MakeAbsoluteSD2)
DEFINE_FUNC11(MakeAbsoluteSD)
DEFINE_FUNC3(MakeSelfRelativeSD)
DEFINE_FUNC2(MapGenericMask)
DEFINE_FUNC1(NotifyBootConfigStatus)
DEFINE_FUNC2(NotifyChangeEventLog)
DEFINE_FUNC3(ObjectCloseAuditAlarmA)
DEFINE_FUNC3(ObjectCloseAuditAlarmW)
DEFINE_FUNC3(ObjectDeleteAuditAlarmA)
DEFINE_FUNC3(ObjectDeleteAuditAlarmW)
DEFINE_FUNC12(ObjectOpenAuditAlarmA)
DEFINE_FUNC12(ObjectOpenAuditAlarmW)
DEFINE_FUNC6(ObjectPrivilegeAuditAlarmA)
DEFINE_FUNC6(ObjectPrivilegeAuditAlarmW)
DEFINE_FUNC2(OpenBackupEventLogA)
DEFINE_FUNC2(OpenBackupEventLogW)
DEFINE_FUNC3(OpenEncryptedFileRawA)
DEFINE_FUNC3(OpenEncryptedFileRawW)
DEFINE_FUNC2(OpenEventLogA)
DEFINE_FUNC2(OpenEventLogW)
DEFINE_FUNC3(OpenProcessToken)
//DEFINE_FUNC3(OpenSCManagerA)
//DEFINE_FUNC3(OpenSCManagerW)
DEFINE_FUNC3(OpenServiceA)
DEFINE_FUNC3(OpenServiceW)
DEFINE_FUNC4(OpenThreadToken)
DEFINE_FUNC1(OpenTraceA)
DEFINE_FUNC1(OpenTraceW)
DEFINE_FUNC3(PrivilegeCheck)
DEFINE_FUNC5(PrivilegedServiceAuditAlarmA)
DEFINE_FUNC5(PrivilegedServiceAuditAlarmW)
DEFINE_FUNC4(ProcessTrace)
DEFINE_FUNC3(QueryAllTracesA)
DEFINE_FUNC3(QueryAllTracesW)
DEFINE_FUNC2(QueryRecoveryAgentsOnEncryptedFile)
DEFINE_FUNC5(QueryServiceConfig2A)
DEFINE_FUNC5(QueryServiceConfig2W)
DEFINE_FUNC4(QueryServiceConfigA)
DEFINE_FUNC4(QueryServiceConfigW)
DEFINE_FUNC4(QueryServiceLockStatusA)
DEFINE_FUNC4(QueryServiceLockStatusW)
DEFINE_FUNC5(QueryServiceObjectSecurity)
DEFINE_FUNC2(QueryServiceStatus)
DEFINE_FUNC5(QueryServiceStatusEx)
DEFINE_FUNC2(QueryUsersOnEncryptedFile)
DEFINE_FUNC3(ReadEncryptedFileRaw)
DEFINE_FUNC7(ReadEventLogA)
DEFINE_FUNC7(ReadEventLogW)
//DEFINE_FUNC1(RegCloseKey)
DEFINE_FUNC3(RegConnectRegistryA)
DEFINE_FUNC3(RegConnectRegistryW)
DEFINE_FUNC_REDIR3(RegCreateKeyA)
//DEFINE_FUNC_REDIR9(RegCreateKeyExA)
//DEFINE_FUNC_REDIR9(RegCreateKeyExW)
DEFINE_FUNC_REDIR3(RegCreateKeyW)
DEFINE_FUNC_REDIR2(RegDeleteKeyA)
DEFINE_FUNC_REDIR2(RegDeleteKeyW)
DEFINE_FUNC_REDIR4(RegDeleteKeyExA)
DEFINE_FUNC_REDIR4(RegDeleteKeyExW)
DEFINE_FUNC_REDIR2(RegDeleteValueA)
DEFINE_FUNC_REDIR2(RegDeleteValueW)
DEFINE_FUNC0(RegDisablePredefinedCache)
DEFINE_FUNC_REDIR4(RegEnumKeyA)
DEFINE_FUNC_REDIR8(RegEnumKeyExA)
DEFINE_FUNC_REDIR8(RegEnumKeyExW)
DEFINE_FUNC_REDIR4(RegEnumKeyW)
DEFINE_FUNC_REDIR8(RegEnumValueA)
DEFINE_FUNC_REDIR8(RegEnumValueW)
DEFINE_FUNC_REDIR1(RegFlushKey)
DEFINE_FUNC_REDIR4(RegGetKeySecurity)
DEFINE_FUNC_REDIR3(RegLoadKeyA)
DEFINE_FUNC_REDIR3(RegLoadKeyW)
DEFINE_FUNC_REDIR5(RegNotifyChangeKeyValue)
DEFINE_FUNC2(RegOpenCurrentUser)
DEFINE_FUNC_REDIR3(RegOpenKeyA)
DEFINE_FUNC_REDIR5(RegOpenKeyExA)
DEFINE_FUNC_REDIR5(RegOpenKeyExW)
DEFINE_FUNC_REDIR3(RegOpenKeyW)
DEFINE_FUNC4(RegOpenUserClassesRoot)
//DEFINE_FUNC2(RegOverridePredefKey)
DEFINE_FUNC_REDIR12(RegQueryInfoKeyA)
DEFINE_FUNC_REDIR12(RegQueryInfoKeyW)
DEFINE_FUNC_REDIR5(RegQueryMultipleValuesA)
DEFINE_FUNC_REDIR5(RegQueryMultipleValuesW)
DEFINE_FUNC_REDIR4(RegQueryValueA)
DEFINE_FUNC_REDIR6(RegQueryValueExA)
DEFINE_FUNC_REDIR6(RegQueryValueExW)
DEFINE_FUNC_REDIR4(RegQueryValueW)
DEFINE_FUNC_REDIR4(RegReplaceKeyA)
DEFINE_FUNC_REDIR4(RegReplaceKeyW)
DEFINE_FUNC_REDIR3(RegRestoreKeyA)
DEFINE_FUNC_REDIR3(RegRestoreKeyW)
DEFINE_FUNC_REDIR3(RegSaveKeyA)
DEFINE_FUNC_REDIR3(RegSaveKeyW)
DEFINE_FUNC_REDIR3(RegSetKeySecurity)
DEFINE_FUNC_REDIR5(RegSetValueA)
DEFINE_FUNC_REDIR6(RegSetValueExA)
DEFINE_FUNC_REDIR6(RegSetValueExW)
DEFINE_FUNC_REDIR5(RegSetValueW)
DEFINE_FUNC_REDIR2(RegUnLoadKeyA)
DEFINE_FUNC_REDIR2(RegUnLoadKeyW)
DEFINE_FUNC2(RegisterEventSourceA)
DEFINE_FUNC2(RegisterEventSourceW)
DEFINE_FUNC2(RegisterServiceCtrlHandlerA)
DEFINE_FUNC3(RegisterServiceCtrlHandlerExA)
DEFINE_FUNC3(RegisterServiceCtrlHandlerExW)
DEFINE_FUNC2(RegisterServiceCtrlHandlerW)
DEFINE_FUNC8(RegisterTraceGuidsA)
DEFINE_FUNC8(RegisterTraceGuidsW)
DEFINE_FUNC1(RemoveTraceCallback)
DEFINE_FUNC2(RemoveUsersFromEncryptedFile)
DEFINE_FUNC9(ReportEventA)
DEFINE_FUNC9(ReportEventW)
DEFINE_FUNC0(RevertToSelf)
DEFINE_FUNC4(SetAclInformation)
DEFINE_FUNC6(SetEntriesInAccessListA)
DEFINE_FUNC6(SetEntriesInAccessListW)
DEFINE_FUNC4(SetEntriesInAclA)
DEFINE_FUNC4(SetEntriesInAclW)
DEFINE_FUNC6(SetEntriesInAuditListA)
DEFINE_FUNC6(SetEntriesInAuditListW)
DEFINE_FUNC3(SetFileSecurityA)
DEFINE_FUNC3(SetFileSecurityW)
DEFINE_FUNC3(SetKernelObjectSecurity)
DEFINE_FUNC7(SetNamedSecurityInfoA)
DEFINE_FUNC9(SetNamedSecurityInfoExA)
DEFINE_FUNC9(SetNamedSecurityInfoExW)
DEFINE_FUNC7(SetNamedSecurityInfoW)
DEFINE_FUNC5(SetPrivateObjectSecurity)
DEFINE_FUNC6(SetPrivateObjectSecurityEx)
DEFINE_FUNC3(SetSecurityDescriptorControl)
DEFINE_FUNC4(SetSecurityDescriptorDacl)
DEFINE_FUNC3(SetSecurityDescriptorGroup)
DEFINE_FUNC3(SetSecurityDescriptorOwner)
DEFINE_FUNC2(SetSecurityDescriptorRMControl)
DEFINE_FUNC4(SetSecurityDescriptorSacl)
DEFINE_FUNC7(SetSecurityInfo)
DEFINE_FUNC9(SetSecurityInfoExA)
DEFINE_FUNC9(SetSecurityInfoExW)
DEFINE_FUNC4(SetServiceBits)
DEFINE_FUNC3(SetServiceObjectSecurity)
DEFINE_FUNC2(SetServiceStatus)
DEFINE_FUNC2(SetThreadToken)
DEFINE_FUNC4(SetTokenInformation)
DEFINE_FUNC2(SetTraceCallback)
DEFINE_FUNC1(SetUserFileEncryptionKey)
DEFINE_FUNC3(StartServiceA)
DEFINE_FUNC1(StartServiceCtrlDispatcherA)
DEFINE_FUNC1(StartServiceCtrlDispatcherW)
DEFINE_FUNC3(StartServiceW)
DEFINE_FUNC3(StartTraceA)
DEFINE_FUNC3(StartTraceW)
DEFINE_FUNC3(SystemFunction001)
DEFINE_FUNC3(SystemFunction002)
DEFINE_FUNC2(SystemFunction003)
DEFINE_FUNC3(SystemFunction004)
DEFINE_FUNC3(SystemFunction005)
DEFINE_FUNC2(SystemFunction006)
DEFINE_FUNC2(SystemFunction007)
DEFINE_FUNC3(SystemFunction008)
DEFINE_FUNC3(SystemFunction009)
DEFINE_FUNC3(SystemFunction010)
DEFINE_FUNC3(SystemFunction011)
DEFINE_FUNC3(SystemFunction012)
DEFINE_FUNC3(SystemFunction013)
DEFINE_FUNC3(SystemFunction014)
DEFINE_FUNC3(SystemFunction015)
DEFINE_FUNC3(SystemFunction016)
DEFINE_FUNC3(SystemFunction017)
DEFINE_FUNC3(SystemFunction018)
DEFINE_FUNC3(SystemFunction019)
DEFINE_FUNC3(SystemFunction020)
DEFINE_FUNC3(SystemFunction021)
DEFINE_FUNC3(SystemFunction022)
DEFINE_FUNC3(SystemFunction023)
DEFINE_FUNC3(SystemFunction024)
DEFINE_FUNC3(SystemFunction025)
DEFINE_FUNC3(SystemFunction026)
DEFINE_FUNC3(SystemFunction027)
DEFINE_FUNC2(SystemFunction028)
DEFINE_FUNC2(SystemFunction029)
DEFINE_FUNC2(SystemFunction030)
DEFINE_FUNC2(SystemFunction031)
DEFINE_FUNC2(SystemFunction032)
DEFINE_FUNC2(SystemFunction033)
DEFINE_FUNC3(SystemFunction034)
DEFINE_FUNC3(TraceEvent)
DEFINE_FUNC5(TraceEventInstance)
DEFINE_FUNC6(TrusteeAccessToObjectA)
DEFINE_FUNC6(TrusteeAccessToObjectW)
DEFINE_FUNC1(UnlockServiceDatabase)
DEFINE_FUNC2(UnregisterTraceGuids)
DEFINE_FUNC3(WriteEncryptedFileRaw)
DEFINE_FUNC_REDIR2(RegDeleteTreeA)
DEFINE_FUNC_REDIR2(RegDeleteTreeW)
DEFINE_FUNC0(RegDisablePredefinedCacheEx)
DEFINE_FUNC_REDIR7(RegGetValueA)
DEFINE_FUNC_REDIR7(RegGetValueW)
DEFINE_FUNC_REDIR7(RegLoadMUIStringA)
DEFINE_FUNC_REDIR7(RegLoadMUIStringW)
DEFINE_FUNC_REDIR4(RegSaveKeyExA)
DEFINE_FUNC_REDIR4(RegSaveKeyExW)
