#include "dllstub_def.h"

static const char DLL_NAME[]="psapi.nt.dll";

DEFINE_FUNC1(EmptyWorkingSet)
DEFINE_FUNC3(EnumDeviceDrivers)
DEFINE_FUNC2(EnumPageFilesA)
DEFINE_FUNC2(EnumPageFilesW)
DEFINE_FUNC4(EnumProcessModules)
DEFINE_FUNC3(EnumProcesses)
DEFINE_FUNC3(GetDeviceDriverBaseNameA)
DEFINE_FUNC3(GetDeviceDriverBaseNameW)
DEFINE_FUNC3(GetDeviceDriverFileNameA)
DEFINE_FUNC3(GetDeviceDriverFileNameW)
DEFINE_FUNC4(GetMappedFileNameA)
DEFINE_FUNC4(GetMappedFileNameW)
DEFINE_FUNC4(GetModuleBaseNameA)
DEFINE_FUNC4(GetModuleBaseNameW)
DEFINE_FUNC4(GetModuleFileNameExA)
DEFINE_FUNC4(GetModuleFileNameExW)
DEFINE_FUNC4(GetModuleInformation)
DEFINE_FUNC2(GetPerformanceInfo)
DEFINE_FUNC3(GetProcessImageFileNameA)
DEFINE_FUNC3(GetProcessImageFileNameW)
DEFINE_FUNC3(GetProcessMemoryInfo)
DEFINE_FUNC3(GetWsChanges)
DEFINE_FUNC1(InitializeProcessForWsWatch)
DEFINE_FUNC3(QueryWorkingSet)
DEFINE_FUNC3(QueryWorkingSetEx)
