#include "dllstub_def.h"

static const char DLL_NAME[]="mswsock.nt.dll";

DEFINE_FUNC8(AcceptEx)
DEFINE_FUNC3(EnumProtocolsA)
DEFINE_FUNC3(EnumProtocolsW)
DEFINE_FUNC8(GetAcceptExSockaddrs)
DEFINE_FUNC10(GetAddressByNameA)
DEFINE_FUNC10(GetAddressByNameW)
DEFINE_FUNC3(GetNameByTypeA)
DEFINE_FUNC3(GetNameByTypeW)
DEFINE_FUNC7(GetServiceA)
DEFINE_FUNC7(GetServiceW)
DEFINE_FUNC2(GetTypeByNameA)
DEFINE_FUNC2(GetTypeByNameW)
DEFINE_FUNC3(MigrateWinsockConfiguration)
DEFINE_FUNC3(NPLoadNameSpaces)
DEFINE_FUNC6(SetServiceA)
DEFINE_FUNC6(SetServiceW)
DEFINE_FUNC7(TransmitFile)
DEFINE_FUNC4(WSARecvEx)
DEFINE_FUNC5(dn_expand)
DEFINE_FUNC1(getnetbyname)
DEFINE_FUNC1(inet_network)
DEFINE_FUNC6(rcmd)
DEFINE_FUNC6(rexec)
DEFINE_FUNC1(rresvport)
DEFINE_FUNC2(s_perror)
DEFINE_FUNC2(sethostname)
